spring:
  thymeleaf:
      mode: LEGACYHTML5
  resources:
    chain:
      enabled: true
  datasource:
    url: jdbc:mysql://****
    username: root
    password: 
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  http:
    multipart:
      max-file-size: 102400kb
      max-request-size: 102400kb
server:
  port: 8082
  max-http-header-size: 65536
  tomcat:
    max-http-post-size: 4194304
  jetty:
    max-http-post-size: 4194304
